#!/bin/bash
# This script retrieves an IP address
# from a meshnode-database, running some version of
# https://github.com/sudomesh/meshnode-database
# Once an IP is retrieved, this script triggers 
# the configuration of this node with the correct
# MESH IP and other related settings stored in
# /opt/mesh/zeroconf

# default configs for People's Open Network
LOG="/dev/stdout"
MESHNODEDB="secrets.peoplesopen.net"
USER="deployer"
PASS="praisebob"
POSTURL="https://$USER:$PASS@$MESHNODEDB/nodes"
OSTYPE="debian" # TODO detect

json_parse() {
  if [ "$OSTYPE" == "debian" ]; then

    json_parse_debian $@

  else

    json_parse_openwrt $@

  fi
}

json_parse_debian() {
  echo $1
}

json_parse_openwrt() {
  . "jshn.sh"

   # parse the json response
   json_load "$MESHNODE_DATA"
   json_select data 
   json_get_var MESHIP mesh_addr_ipv4 
   json_get_var MESHBLOCK open_subnet_ipv4 
   echo "recieved mesh IP:" $MESHIP >>$LOG
   echo "recieved mesh block:" $MESHBLOCK"/26" >>$LOG

}

retrieve_ip() {

    echo "retrieving an IP address from" $MESHNODEDB >>$LOG

    if ping -q -c 1 -W 1 $MESHNODEDB >/dev/null; then
        echo $MESHNODEDB "is reachable" >>$LOG
    else
        echo $MESHNODEDB "is not reachable" >>$LOG
        exit 1
    fi

    # make a post request to meshnode-databse
    echo "posting to" $POSTURL >>$LOG
    MESHNODE_DATA=$(curl -X POST -H "Content-Type: application/x-www-form-urlencoded" --data-urlencode data='{"type":"node", "debug":true}' $POSTURL )

    json_parse $MESHNODE_DATA

}

retrieve_ip
