#!/bin/bash
# This script retrieves an IP address
# from a meshnode-database, running some version of
# https://github.com/sudomesh/meshnode-database
# Once an IP is retrieved, this script triggers 
# the configuration of this node with the correct
# MESH IP and other related settings stored in
# /opt/mesh/zeroconf

# default configs for People's Open Network
LOG="/dev/stdout"
MESHNODEDB="secrets.peoplesopen.net"
USER="deployer"
PASS="praisebob"
POSTURL="https://$USER:$PASS@$MESHNODEDB/nodes"
OSTYPE="debian" # TODO detect

ESSID="pplsopen.net-node2node"
BSSID=CA:FE:C0:DE:F0:0D
IFACE=$1

json_parse() {
  if [ "$OSTYPE" == "debian" ]; then

    json_parse_debian $@

  else

    json_parse_openwrt $@

  fi
}

json_parse_debian() {
  MESHIP=$(echo $1 | jq -r '.data.mesh_addr_ipv4')
  MESHBLOCK=$(echo $1 | jq -r '.data.open_subnet_ipv4')
  echo "received mesh IP:" $MESHIP
  echo "received mesh block:" $MESHBLOCK"/26"
}

json_parse_openwrt() {
  . "jshn.sh"

   # parse the json response
   json_load "$MESHNODE_DATA"
   json_select data 
   json_get_var MESHIP mesh_addr_ipv4 
   json_get_var MESHBLOCK open_subnet_ipv4 
   echo "received mesh IP:" $MESHIP >>$LOG
   echo "received mesh block:" $MESHBLOCK"/26" >>$LOG

}

retrieve_ip() {

    echo "retrieving an IP address from" $MESHNODEDB >>$LOG

    if ping -q -c 1 -W 1 $MESHNODEDB >/dev/null; then
        echo $MESHNODEDB "is reachable" >>$LOG
    else
        echo $MESHNODEDB "is not reachable" >>$LOG
        exit 1
    fi

    # make a post request to meshnode-databse
    echo "posting to" $POSTURL >>$LOG
    MESHNODE_DATA=$(curl -X POST -H "Content-Type: application/x-www-form-urlencoded" --data-urlencode data='{"type":"node", "debug":true}' $POSTURL )

    json_parse $MESHNODE_DATA

}

if [ $2 ]; then
    MESHIP=$2
    echo "mesh IP address manually set to $MESHIP"
else
    retrieve_ip
fi

# Stop Network Manager from managing your interface
NM_CONF=/etc/NetworkManager/NetworkManager.conf
LINE_1="[keyfile]"
grep -qF -- "$LINE_1" "$NM_CONF" || echo "$LINE_1" >> "$NM_CONF"
LINE_2="unmanaged-devices=interface-name:$IFACE"
grep -qF -- "$LINE_2" "$NM_CONF" || echo "$LINE_2" >> "$NM_CONF"

# Add exit nodes as dns servers, allows name resolution over mesh
DNS_CONF=/etc/resolvconf/resolv.conf.d/tail
DNS_1="nameserver 100.64.0.43"
DNS_2="nameserver 100.64.0.42"
grep -qF -- "$DNS_1" "$DNS_CONF" || echo "$DNS_1" >> "$DNS_CONF"
grep -qF -- "$DNS_2" "$DNS_CONF" || echo "$DNS_2" >> "$DNS_CONF"

/etc/init.d/network-manager restart

ip link set $IFACE down 
ip addr add $MESHIP/32 dev $IFACE
ip link set $IFACE up 

iwconfig $IFACE essid $ESSID ap $BSSID channel 6 mode ad-hoc

#babeld $IFACE
